on:
  workflow_dispatch:
  push:
    branches: [ develop ]

permissions:
  id-token: write

jobs:
  terraform-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando Credencial AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::944710019594:role/github-actions-terraform
          aws-region: us-east-1
      - name: CheckOut Source Code
        uses: actions/checkout@v2
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan